# Generated by Django 3.2.1 on 2021-05-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_datamodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=10)),
                ('relay', models.CharField(max_length=3)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='DataModel',
        ),
    ]
